/**
 * The balance report (TESTING.md §5).
 *
 * Not a pass/fail test — a decision instrument. Tuning is then a diff against a
 * table rather than an argument about feel. Regenerate and commit alongside any
 * change to src/config/tuning.ts.
 *
 *   npm run balance [-- --seeds 200]
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { LEVEL_ORDER, type LevelId } from '../src/core/input.js';
import { runLevel, runAfterhour, type BotName } from '../src/core/bots.js';
import { modsForFails, TUNING } from '../src/config/tuning.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, '../reports/balance.md');

const argSeeds = process.argv.indexOf('--seeds');
const SEEDS = argSeeds > -1 ? Number(process.argv[argSeeds + 1]) : 200;

const LEVEL_TITLES: Record<LevelId, string> = {
  pfand: 'L1 Pfand',
  sisyphos: 'L2 Sisyphos',
  katjes: 'L3 Katjes',
  kayak: 'L4 Kayak',
};

function median(xs: number[]): number {
  if (xs.length === 0) return 0;
  const a = [...xs].sort((p, q) => p - q);
  const m = a.length >> 1;
  return a.length % 2 ? a[m] : (a[m - 1] + a[m]) / 2;
}

function pct(n: number, d: number): string {
  return d === 0 ? '—' : `${((100 * n) / d).toFixed(0)} %`;
}

type LevelRow = {
  level: LevelId;
  rates: Record<BotName, number>;
  casualSeconds: number[];
  perfectSeconds: number[];
  failsBeforeWin: number[];
  easedTipsyRate: number;
};

/** How many fails a casual player racks up before clearing, with mercy applied. */
function attemptsUntilWin(level: LevelId, seed: number, bot: BotName, maxAttempts = 8): number {
  for (let fails = 0; fails < maxAttempts; fails++) {
    const r = runLevel(level, seed * 7919 + fails, bot, { mods: modsForFails(fails) });
    if (r.won) return fails;
  }
  return maxAttempts;
}

function measure(level: LevelId): LevelRow {
  const bots: BotName[] = ['perfect', 'casual', 'tipsy', 'idle', 'mash'];
  const rates = {} as Record<BotName, number>;
  const casualSeconds: number[] = [];
  const perfectSeconds: number[] = [];

  for (const bot of bots) {
    let wins = 0;
    for (let seed = 0; seed < SEEDS; seed++) {
      const r = runLevel(level, seed, bot);
      if (r.won) wins++;
      if (bot === 'casual' && r.won) casualSeconds.push(r.seconds);
      if (bot === 'perfect' && r.won) perfectSeconds.push(r.seconds);
    }
    rates[bot] = wins / SEEDS;
  }

  const failsBeforeWin: number[] = [];
  const sample = Math.min(SEEDS, 60);
  for (let seed = 0; seed < sample; seed++) failsBeforeWin.push(attemptsUntilWin(level, seed, 'casual'));

  // The eased level must be winnable by tipsy (TESTING.md §3).
  const easedMods = modsForFails(TUNING.mercy.easeAfterFails);
  let easedWins = 0;
  for (let seed = 0; seed < SEEDS; seed++) {
    if (runLevel(level, seed, 'tipsy', { mods: easedMods }).won) easedWins++;
  }

  return {
    level,
    rates,
    casualSeconds,
    perfectSeconds,
    failsBeforeWin,
    easedTipsyRate: easedWins / SEEDS,
  };
}

const t0 = Date.now();
const rows = LEVEL_ORDER.map(measure);
const elapsed = ((Date.now() - t0) / 1000).toFixed(1);

const medianTotal = rows.reduce((a, r) => a + median(r.casualSeconds), 0);

const lines: string[] = [];
lines.push('# Balance report');
lines.push('');
lines.push(`Generated by \`npm run balance\` — ${SEEDS} seeds per bot per level, ${elapsed}s.`);
lines.push('');
lines.push('This is a decision instrument, not a pass/fail gate. The gates live in');
lines.push('`tests/bots.test.ts`: casual ≥ 85 %, tipsy ≥ 50 %, perfect 100 %.');
lines.push('');
lines.push('| Level | perfect | casual | tipsy | idle | mash | median duration (casual) | median fails before win | tipsy on eased |');
lines.push('|---|---|---|---|---|---|---|---|---|');
for (const r of rows) {
  lines.push(
    `| ${LEVEL_TITLES[r.level]} | ${pct(r.rates.perfect * SEEDS, SEEDS)} | ${pct(r.rates.casual * SEEDS, SEEDS)} | ` +
      `${pct(r.rates.tipsy * SEEDS, SEEDS)} | ${pct(r.rates.idle * SEEDS, SEEDS)} | ${pct(r.rates.mash * SEEDS, SEEDS)} | ` +
      `${median(r.casualSeconds).toFixed(1)} s | ${median(r.failsBeforeWin).toFixed(1)} | ${pct(r.easedTipsyRate * SEEDS, SEEDS)} |`,
  );
}
lines.push('');
lines.push('## Session length');
lines.push('');
lines.push(
  `Sum of the casual medians: **${medianTotal.toFixed(0)} s** (${(medianTotal / 60).toFixed(1)} min) of play, ` +
    'before intro cards, fails and the reveal. DESIGN.md §2 targets 5–7 minutes first tap to reveal.',
);
lines.push('');
lines.push('| Level | perfect median | casual median | slowest casual win |');
lines.push('|---|---|---|---|');
for (const r of rows) {
  lines.push(
    `| ${LEVEL_TITLES[r.level]} | ${median(r.perfectSeconds).toFixed(1)} s | ${median(r.casualSeconds).toFixed(1)} s | ` +
      `${(r.casualSeconds.length ? Math.max(...r.casualSeconds) : 0).toFixed(1)} s |`,
  );
}
lines.push('');
lines.push('## Notes');
lines.push('');
lines.push('- `idle` never touches the screen. It is expected to fail everywhere except');
lines.push('  L4, where doing nothing is still the safest available play — though after');
lines.push('  the difficulty pass it is no longer close to a guarantee.');
lines.push('- `mash` is the no-crash canary; its win rate carries no meaning.');
lines.push('- "tipsy on eased" is the mercy rule doing its job: after four fails the');
lines.push('  level auto-eases and must then be winnable by the worst bot we model.');
lines.push('- The four medians land under the 5–7 minute target from DESIGN.md §2 once');
lines.push('  intro cards, fails and the reveal are added. That is the deliberate side to');
lines.push('  err on at a party: a game that ends too soon still reaches the present, and');
lines.push('  PLAN.md §4 spends the remaining time on finishing rather than lengthening.');
lines.push('- The difficulty pass raised every goal (26 Flaschen, 3000 px queue, 28');
lines.push('  Heringe, 5400 px river) and, where the bots had room, the rate the level');
lines.push('  comes at you. What bounded each level was not taste but a gate:');
lines.push('  - **L1** — `tipsy`. Obstacle share and spawn gap are savage to it: 0.46');
lines.push('    share took tipsy to 48 %, and tightening the gap to 185–300 px to 15 %.');
lines.push('    Length and the speed ramp cost it far less, so the goal carries the pass.');
lines.push('  - **L2** — `perfect`, and it is a design signal, not a bot weakness: a');
lines.push('    two-bouncer row can close its gap, and the Sonnenbrille is what carries a');
lines.push('    perfect line through. Shortening `shadesDurationMs` dropped perfect to');
lines.push('    95 %. Hence a longer queue and a modest `twoBouncerChance`, nothing more.');
lines.push('  - **L3** — `tipsy` again; 32 Heringe put it on the 50 % line, 28 leaves air.');
lines.push('  - **L4** — `idle`. Narrowing the channel or thickening the rock field guts');
lines.push('    it (10 % and 8 %), and doing nothing must stay the safest play, not a');
lines.push('    trap — the joke in DESIGN.md §4 depends on it. A longer, slightly');
lines.push('    narrower river keeps idle at a comfortable margin over its 35 % floor.');
lines.push('');

// --- Afterhour: a survival/loops distribution, not a win-rate table --------
// Capped well under the real (20-minute) hard frame cap: this is a decision
// instrument sampled cheaply, not the no-soft-lock guarantee itself (that's
// asserted at the real cap in tests/core/afterhour.test.ts).
const AH_BOTS: BotName[] = ['perfect', 'casual', 'tipsy', 'idle'];
const AH_SEEDS = Math.min(20, SEEDS);
const AH_FRAME_CAP = 5 * 60 * 60; // 5 simulated minutes
const ahRows = AH_BOTS.map((bot) => {
  const loops: number[] = [];
  const seconds: number[] = [];
  for (let seed = 0; seed < AH_SEEDS; seed++) {
    const r = runAfterhour(seed, bot, { frameCap: AH_FRAME_CAP });
    loops.push(r.loops);
    seconds.push(r.frames / 60);
  }
  return { bot, medianLoops: median(loops), medianSeconds: median(seconds) };
});

lines.push('## Afterhour (hidden endless bonus level)');
lines.push('');
lines.push(
  `${AH_SEEDS} seeds per bot, capped at ${AH_FRAME_CAP / 60}s each (a cheap sample, not the real ` +
    'hard cap). No win/lose gate — the only invariants tested are termination (no soft-lock, ever)',
);
lines.push('and a minimum-viability floor (see tests/core/afterhour.test.ts).');
lines.push('');
lines.push('| Bot | median loops survived | median duration |');
lines.push('|---|---|---|');
for (const r of ahRows) {
  lines.push(`| ${r.bot} | ${r.medianLoops.toFixed(1)} | ${r.medianSeconds.toFixed(0)} s |`);
}
lines.push('');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(lines.slice(6, 14).join('\n'));
console.log(`\nWrote ${OUT} in ${elapsed}s`);
