/**
 * The balance report (TESTING.md §5).
 *
 * Not a pass/fail test — a decision instrument. Tuning is then a diff against a
 * table rather than an argument about feel. Regenerate and commit alongside any
 * change to src/config/tuning.ts.
 *
 *   npm run balance [-- --seeds 200]
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { LEVEL_ORDER, type LevelId } from '../src/core/input.js';
import { runLevel, runAfterhour, type BotName } from '../src/core/bots.js';
import { modsForFails, TUNING } from '../src/config/tuning.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, '../reports/balance.md');

const argSeeds = process.argv.indexOf('--seeds');
const SEEDS = argSeeds > -1 ? Number(process.argv[argSeeds + 1]) : 200;

const LEVEL_TITLES: Record<LevelId, string> = {
  pfand: 'L1 Pfand',
  sisyphos: 'L2 Sisyphos',
  katjes: 'L3 Katjes',
  kayak: 'L4 Kayak',
};

function median(xs: number[]): number {
  if (xs.length === 0) return 0;
  const a = [...xs].sort((p, q) => p - q);
  const m = a.length >> 1;
  return a.length % 2 ? a[m] : (a[m - 1] + a[m]) / 2;
}

function pct(n: number, d: number): string {
  return d === 0 ? '—' : `${((100 * n) / d).toFixed(0)} %`;
}

type LevelRow = {
  level: LevelId;
  rates: Record<BotName, number>;
  casualSeconds: number[];
  perfectSeconds: number[];
  failsBeforeWin: number[];
  easedTipsyRate: number;
};

/** How many fails a casual player racks up before clearing, with mercy applied. */
function attemptsUntilWin(level: LevelId, seed: number, bot: BotName, maxAttempts = 8): number {
  for (let fails = 0; fails < maxAttempts; fails++) {
    const r = runLevel(level, seed * 7919 + fails, bot, { mods: modsForFails(fails) });
    if (r.won) return fails;
  }
  return maxAttempts;
}

function measure(level: LevelId): LevelRow {
  const bots: BotName[] = ['perfect', 'casual', 'tipsy', 'idle', 'mash'];
  const rates = {} as Record<BotName, number>;
  const casualSeconds: number[] = [];
  const perfectSeconds: number[] = [];

  for (const bot of bots) {
    let wins = 0;
    for (let seed = 0; seed < SEEDS; seed++) {
      const r = runLevel(level, seed, bot);
      if (r.won) wins++;
      if (bot === 'casual' && r.won) casualSeconds.push(r.seconds);
      if (bot === 'perfect' && r.won) perfectSeconds.push(r.seconds);
    }
    rates[bot] = wins / SEEDS;
  }

  const failsBeforeWin: number[] = [];
  const sample = Math.min(SEEDS, 60);
  for (let seed = 0; seed < sample; seed++) failsBeforeWin.push(attemptsUntilWin(level, seed, 'casual'));

  // The eased level must be winnable by tipsy (TESTING.md §3).
  const easedMods = modsForFails(TUNING.mercy.easeAfterFails);
  let easedWins = 0;
  for (let seed = 0; seed < SEEDS; seed++) {
    if (runLevel(level, seed, 'tipsy', { mods: easedMods }).won) easedWins++;
  }

  return {
    level,
    rates,
    casualSeconds,
    perfectSeconds,
    failsBeforeWin,
    easedTipsyRate: easedWins / SEEDS,
  };
}

const t0 = Date.now();
const rows = LEVEL_ORDER.map(measure);
const elapsed = ((Date.now() - t0) / 1000).toFixed(1);

const medianTotal = rows.reduce((a, r) => a + median(r.casualSeconds), 0);

const lines: string[] = [];
lines.push('# Balance report');
lines.push('');
lines.push(`Generated by \`npm run balance\` — ${SEEDS} seeds per bot per level, ${elapsed}s.`);
lines.push('');
lines.push('This is a decision instrument, not a pass/fail gate. The gates live in');
lines.push('`tests/core/bots.test.ts`: perfect ≥ 97 %, casual ≥ 55 %, tipsy on the eased');
lines.push('level ≥ 60 % *and* above its un-eased rate. There is no un-eased `tipsy`');
lines.push('floor any more — see the notes below.');
lines.push('');
lines.push('| Level | perfect (seeds won) | casual | tipsy | idle | mash | median duration (casual) | median fails before win | tipsy on eased |');
lines.push('|---|---|---|---|---|---|---|---|---|');
for (const r of rows) {
  lines.push(
    // The perfect column is a count, not a percentage: 199/200 rounds to
    // "100 %" and would hide exactly the seed worth looking at.
    `| ${LEVEL_TITLES[r.level]} | ${Math.round(r.rates.perfect * SEEDS)}/${SEEDS} | ${pct(r.rates.casual * SEEDS, SEEDS)} | ` +
      `${pct(r.rates.tipsy * SEEDS, SEEDS)} | ${pct(r.rates.idle * SEEDS, SEEDS)} | ${pct(r.rates.mash * SEEDS, SEEDS)} | ` +
      `${median(r.casualSeconds).toFixed(1)} s | ${median(r.failsBeforeWin).toFixed(1)} | ${pct(r.easedTipsyRate * SEEDS, SEEDS)} |`,
  );
}
lines.push('');
lines.push('## Session length');
lines.push('');
lines.push(
  `Sum of the casual medians: **${medianTotal.toFixed(0)} s** (${(medianTotal / 60).toFixed(1)} min) of play, ` +
    'before intro cards, fails and the reveal. DESIGN.md §2 targets 5–7 minutes first tap to reveal.',
);
lines.push('');
lines.push('| Level | perfect median | casual median | slowest casual win |');
lines.push('|---|---|---|---|');
for (const r of rows) {
  lines.push(
    `| ${LEVEL_TITLES[r.level]} | ${median(r.perfectSeconds).toFixed(1)} s | ${median(r.casualSeconds).toFixed(1)} s | ` +
      `${(r.casualSeconds.length ? Math.max(...r.casualSeconds) : 0).toFixed(1)} s |`,
  );
}
lines.push('');
lines.push('## Notes');
lines.push('');
lines.push('- `idle` never touches the screen and now loses everywhere, L4 included.');
lines.push('  Doing nothing is still the *safest* play there — it survives several times');
lines.push('  longer than `mash` — but the narrower channel means it no longer reaches');
lines.push('  the Spree on its own. That relationship, not a win rate, is what');
lines.push('  tests/core/bots.test.ts pins down.');
lines.push('- The `perfect` column is a count on purpose. `perfect` is greedy, not an');
lines.push('  oracle — it scores the next moment, not the next ten — so on the tuned L1');
lines.push('  and L2 it corners itself on about one seed in two hundred. Those seeds are');
lines.push('  fair: they pass the no-unavoidable-death lookahead in fuzz.test.ts at every');
lines.push('  sampled frame. Hence a 97 % gate and a count here, where 199/200 cannot');
lines.push('  round itself into looking like 200/200.');
lines.push('- `mash` is the no-crash canary; its win rate carries no meaning.');
lines.push('- "tipsy on eased" is the mercy rule doing its job: after four fails the');
lines.push('  level auto-eases and must then be winnable by the worst bot we model.');
lines.push('- The medians sit inside the 5–7 minute target from DESIGN.md §2 once intro');
lines.push('  cards, fails and the reveal are added — and the second pass moved them the');
lines.push('  right way: the levels now take long enough to be worth clearing.');
lines.push('- **Second difficulty pass.** The first pass was bounded by the old gates');
lines.push('  (casual ≥ 85 %, tipsy ≥ 50 %), and the result played too easy: nothing but');
lines.push('  L4 could realistically be lost. Those two gates were the wrong instrument —');
lines.push('  what has to hold is *he reaches the reveal*, and that is guaranteed by the');
lines.push('  mercy rules (skip after 2 fails, auto-ease after 4), not by a level nobody');
lines.push('  can lose. So the un-eased `tipsy` floor is gone, the `casual` floor dropped');
lines.push('  to 55 %, and the mercy ease was strengthened to carry the promise instead');
lines.push('  (density ×0.65, speed ×0.82, +2 lives — was ×0.8 / ×0.9 / +1).');
lines.push('  Goals: 38 Flaschen, 4300 px queue, 36 Heringe, 6400 px river. Faster');
lines.push('  everywhere, denser everywhere, and a smaller Tüte in L3.');
lines.push('  What bounds each level now:');
lines.push('  - **L1** — the speed ramp (6.0 px/s², cap 330) is what makes the back half');
lines.push('    hurt, and **two lives instead of three** is what stops a good run from');
lines.push('    being unloseable: it moved `casual` from 97 % to 88 % on its own.');
lines.push('  - **L2** — the `perfect` bot. A two-bouncer row can close its own gap, so');
lines.push('    `bouncerSpeedMax` is capped at 130: at 150 the fuzz test found a row');
lines.push('    configuration no input escaped, which is a level bug, not difficulty.');
lines.push('    Below that cap the level is fair but not gentle.');
lines.push('  - **L3** — `perfect` at the spawn rate: 0.50 s → 0.26 s over 32 s, with a');
lines.push('    56 px Tüte and a third of everything falling being vegetables.');
lines.push('  - **L4** — the Ruhe economy. A narrower channel (80 → 55 px half-width)');
lines.push('    over a longer river is what did the work; the rock field was left thin');
lines.push('    on purpose, because rocks punish the panicking player twice.');
lines.push('');

// --- Afterhour: a survival/loops distribution, not a win-rate table --------
// Capped well under the real (20-minute) hard frame cap: this is a decision
// instrument sampled cheaply, not the no-soft-lock guarantee itself (that's
// asserted at the real cap in tests/core/afterhour.test.ts).
const AH_BOTS: BotName[] = ['perfect', 'casual', 'tipsy', 'idle'];
const AH_SEEDS = Math.min(20, SEEDS);
const AH_FRAME_CAP = 5 * 60 * 60; // 5 simulated minutes
const ahRows = AH_BOTS.map((bot) => {
  const loops: number[] = [];
  const seconds: number[] = [];
  for (let seed = 0; seed < AH_SEEDS; seed++) {
    const r = runAfterhour(seed, bot, { frameCap: AH_FRAME_CAP });
    loops.push(r.loops);
    seconds.push(r.frames / 60);
  }
  return { bot, medianLoops: median(loops), medianSeconds: median(seconds) };
});

lines.push('## Afterhour (hidden endless bonus level)');
lines.push('');
lines.push(
  `${AH_SEEDS} seeds per bot, capped at ${AH_FRAME_CAP / 60}s each (a cheap sample, not the real ` +
    'hard cap). No win/lose gate — the only invariants tested are termination (no soft-lock, ever)',
);
lines.push('and a minimum-viability floor (see tests/core/afterhour.test.ts).');
lines.push('');
lines.push('| Bot | median loops survived | median duration |');
lines.push('|---|---|---|');
for (const r of ahRows) {
  lines.push(`| ${r.bot} | ${r.medianLoops.toFixed(1)} | ${r.medianSeconds.toFixed(0)} s |`);
}
lines.push('');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(lines.slice(6, 14).join('\n'));
console.log(`\nWrote ${OUT} in ${elapsed}s`);
